/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinedb;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author theam
 */
public class CustomerMenu extends javax.swing.JFrame {
String loggedUname=null;
String loggedUid=null;
    /**
     * Creates new form CustomerMenu
     */
    public CustomerMenu() {
        initComponents();
    }
    
    public void OnStart(String uid,String name){
        loggedUname=name;
        loggedUid=uid;
    }
    private void SetHoverThemeFor(JLabel lb,JPanel pan){
        pan.setBackground(new java.awt.Color(204,204,204));
        lb.setForeground(new java.awt.Color(0,0,0));
    }
    private void ResetHoverThemeFor(JLabel lb,JPanel pan){
        pan.setBackground(new java.awt.Color(0,102,204));
        lb.setForeground(new java.awt.Color(255,255,255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmpan = new javax.swing.JPanel();
        bfpan = new javax.swing.JPanel();
        bflab = new javax.swing.JLabel();
        ybpan = new javax.swing.JPanel();
        yblab = new javax.swing.JLabel();
        fmpan = new javax.swing.JPanel();
        fmlab = new javax.swing.JLabel();
        mapan = new javax.swing.JPanel();
        malab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bckLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bfpan.setBackground(new java.awt.Color(0, 102, 204));

        bflab.setForeground(new java.awt.Color(255, 255, 255));
        bflab.setText("            BOOK FLIGHT");
        bflab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bflab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bfmclk(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BFMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BFMEX(evt);
            }
        });

        javax.swing.GroupLayout bfpanLayout = new javax.swing.GroupLayout(bfpan);
        bfpan.setLayout(bfpanLayout);
        bfpanLayout.setHorizontalGroup(
            bfpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bflab, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        bfpanLayout.setVerticalGroup(
            bfpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bflab, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        ybpan.setBackground(new java.awt.Color(0, 102, 204));

        yblab.setForeground(new java.awt.Color(255, 255, 255));
        yblab.setText("           YOUR BOOKINGS");
        yblab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yblab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yblabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yblabBFMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yblabBFMEX(evt);
            }
        });

        javax.swing.GroupLayout ybpanLayout = new javax.swing.GroupLayout(ybpan);
        ybpan.setLayout(ybpanLayout);
        ybpanLayout.setHorizontalGroup(
            ybpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yblab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        ybpanLayout.setVerticalGroup(
            ybpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yblab, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        fmpan.setBackground(new java.awt.Color(0, 102, 204));

        fmlab.setForeground(new java.awt.Color(255, 255, 255));
        fmlab.setText("      FLIGHT MANAGEMENT");
        fmlab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fmlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fmlabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fmlabBFMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fmlabBFMEX(evt);
            }
        });

        javax.swing.GroupLayout fmpanLayout = new javax.swing.GroupLayout(fmpan);
        fmpan.setLayout(fmpanLayout);
        fmpanLayout.setHorizontalGroup(
            fmpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fmlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        fmpanLayout.setVerticalGroup(
            fmpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fmlab, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        mapan.setBackground(new java.awt.Color(0, 102, 204));

        malab.setForeground(new java.awt.Color(255, 255, 255));
        malab.setText("         MANAGE ACCOUNT");
        malab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        malab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                malabBFMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                malabBFMEX(evt);
            }
        });

        javax.swing.GroupLayout mapanLayout = new javax.swing.GroupLayout(mapan);
        mapan.setLayout(mapanLayout);
        mapanLayout.setHorizontalGroup(
            mapanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(malab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        mapanLayout.setVerticalGroup(
            mapanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(malab, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        cmpan.setBackground(new java.awt.Color(0,0,0,150));

        javax.swing.GroupLayout cmpanLayout = new javax.swing.GroupLayout(cmpan);
        cmpan.setLayout(cmpanLayout);
        cmpanLayout.setHorizontalGroup(
            cmpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cmpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bfpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ybpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fmpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        cmpanLayout.setVerticalGroup(
            cmpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmpanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bfpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ybpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fmpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(cmpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 760, 290));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    LOGOUT");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 702, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        bckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/3d_airport_interior_11.jpg"))); // NOI18N
        getContentPane().add(bckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BFMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BFMEN
        // TODO add your handling code here:
        SetHoverThemeFor(bflab,bfpan);
    }//GEN-LAST:event_BFMEN

    private void BFMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BFMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(bflab,bfpan);
    }//GEN-LAST:event_BFMEX

    private void yblabBFMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yblabBFMEN
        // TODO add your handling code here:
        SetHoverThemeFor(yblab,ybpan);
    }//GEN-LAST:event_yblabBFMEN

    private void yblabBFMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yblabBFMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(yblab,ybpan);
    }//GEN-LAST:event_yblabBFMEX

    private void fmlabBFMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmlabBFMEN
        // TODO add your handling code here:
        SetHoverThemeFor(fmlab,fmpan);
    }//GEN-LAST:event_fmlabBFMEN

    private void fmlabBFMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmlabBFMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(fmlab,fmpan);
    }//GEN-LAST:event_fmlabBFMEX

    private void malabBFMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malabBFMEN
        // TODO add your handling code here:
        SetHoverThemeFor(malab,mapan);
    }//GEN-LAST:event_malabBFMEN

    private void malabBFMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malabBFMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(malab,mapan);
    }//GEN-LAST:event_malabBFMEX

    private void malabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malabMouseClicked
        // TODO add your handling code here:
        C_manageAccount cma=new C_manageAccount();
        cma.OnStart(loggedUid, loggedUname);
        cma.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_malabMouseClicked

    private void yblabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yblabMouseClicked
        // TODO add your handling code here:
        customerHistory ch=new customerHistory();
        ch.OnStart(loggedUid, loggedUname);
        ch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yblabMouseClicked

    private void bfmclk(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bfmclk
        // TODO add your handling code here:
        bookflight bf=new  bookflight();
        bf.OnStart(loggedUid, loggedUname);
        bf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bfmclk

    private void fmlabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmlabMouseClicked
        // TODO add your handling code here:
        C_CF cf=new C_CF();
        cf.OnStart(loggedUid, loggedUname);
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fmlabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckLabel;
    private javax.swing.JLabel bflab;
    private javax.swing.JPanel bfpan;
    private javax.swing.JPanel cmpan;
    private javax.swing.JLabel fmlab;
    private javax.swing.JPanel fmpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel malab;
    private javax.swing.JPanel mapan;
    private javax.swing.JLabel yblab;
    private javax.swing.JPanel ybpan;
    // End of variables declaration//GEN-END:variables
}
