/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinedb;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expan = new javax.swing.JPanel();
        exitlab = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdtf = new javax.swing.JPasswordField();
        logpan = new javax.swing.JPanel();
        loglab = new javax.swing.JLabel();
        signpan = new javax.swing.JPanel();
        signlab = new javax.swing.JLabel();
        statuslab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minlab = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        expan.setBackground(new java.awt.Color(0, 102, 204));
        expan.setToolTipText("");

        exitlab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitlab.setForeground(new java.awt.Color(255, 255, 255));
        exitlab.setText("     X");
        exitlab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitlabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EBMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitlabMouseExited(evt);
            }
        });

        javax.swing.GroupLayout expanLayout = new javax.swing.GroupLayout(expan);
        expan.setLayout(expanLayout);
        expanLayout.setHorizontalGroup(
            expanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        expanLayout.setVerticalGroup(
            expanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expanLayout.createSequentialGroup()
                .addComponent(exitlab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(expan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");

        nametf.setBackground(new java.awt.Color(102, 102, 102));
        nametf.setForeground(new java.awt.Color(204, 255, 255));
        nametf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametf.setBorder(null);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");

        pwdtf.setBackground(new java.awt.Color(102, 102, 102));
        pwdtf.setForeground(new java.awt.Color(204, 255, 255));
        pwdtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwdtf.setBorder(null);

        logpan.setBackground(new java.awt.Color(0, 102, 204));
        logpan.setToolTipText("");

        loglab.setForeground(new java.awt.Color(255, 255, 255));
        loglab.setText("          LOGIN");
        loglab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loglab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loglabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LBHEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LBHEX(evt);
            }
        });

        javax.swing.GroupLayout logpanLayout = new javax.swing.GroupLayout(logpan);
        logpan.setLayout(logpanLayout);
        logpanLayout.setHorizontalGroup(
            logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loglab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        logpanLayout.setVerticalGroup(
            logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loglab, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        signpan.setBackground(new java.awt.Color(0, 102, 204));

        signlab.setForeground(new java.awt.Color(255, 255, 255));
        signlab.setText("         SIGN UP");
        signlab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signlabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SUMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SUMEX(evt);
            }
        });

        javax.swing.GroupLayout signpanLayout = new javax.swing.GroupLayout(signpan);
        signpan.setLayout(signpanLayout);
        signpanLayout.setHorizontalGroup(
            signpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        signpanLayout.setVerticalGroup(
            signpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        statuslab.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nametf)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pwdtf)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statuslab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statuslab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(logpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/icons8-administrator-male-48.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0,0,0,150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 360, 300));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        minlab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minlab.setForeground(new java.awt.Color(255, 255, 255));
        minlab.setText("    -");
        minlab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minlabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 609, Short.MAX_VALUE)
                .addComponent(minlab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/logbck.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitlabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitlabMouseClicked

    private void minlabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minlabMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minlabMouseClicked

    private void signlabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signlabMouseClicked
        // TODO add your handling code here:
        SignUp su= new SignUp();
        su.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signlabMouseClicked
    private boolean isNotEMP(String str){
        
        if(str==null||str.equals("")){
            return false;
        }else{
            return true;
        }
    }
    private void loglabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loglabMouseClicked
        // TODO add your handling code here:
        String uname=nametf.getText().trim();
        String pwd=pwdtf.getText();
        
        if(isNotEMP(uname)){
            
            if(isNotEMP(pwd)){
                try{
             Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from user where uname='"+uname+"'";
                
               ResultSet rs=stmt.executeQuery(sql);
               
               if(rs.next()){
                   String uid=rs.getString(1);
                   String pwd1=rs.getString(3);
                   String priv=rs.getString(4);
                   if(pwd1.equals(pwd)){
                       
                       if(priv.equals("C")){
                           CustomerMenu cm=new CustomerMenu();
                           cm.OnStart(uid,uname);
                           cm.setVisible(true);
                           this.dispose();
                       }else if(priv.equals("A")){
                           SupportMenu sm=new SupportMenu();
                           sm.OnStart(uid,uname);
                           sm.setVisible(true);
                           this.dispose();
                       }else if(priv.equals("S")){
                           SupportMenu sm=new SupportMenu();
                           sm.OnStart(uid,uname);
                           sm.setVisible(true);
                           this.dispose();
                       }else{
                           statuslab.setText("Error: no valid role found");
                       }
                       
                   }else{
                      statuslab.setText("The password you entered is wrong"); 
                   }
                   
               }else{
                   statuslab.setText("No such user found, check username");
               }
               
                
                
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
            }else{
                statuslab.setText("Enter something in the password field");
            }
            
        }else{
            statuslab.setText("Enter something in the username field");
        }
        
        
       
       
    }//GEN-LAST:event_loglabMouseClicked

    private void LBHEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBHEN
        // TODO add your handling code here:
        logpan.setBackground(new java.awt.Color(204,204,204));
       loglab.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_LBHEN

    private void LBHEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBHEX
        // TODO add your handling code here:
        logpan.setBackground(new java.awt.Color(0,102,204));
       loglab.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LBHEX

    private void EBMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EBMEN
        // TODO add your handling code here:
        expan.setBackground(new java.awt.Color(255,0,0));
        exitlab.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_EBMEN

    private void exitlabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabMouseExited
        // TODO add your handling code here:
        expan.setBackground(new java.awt.Color(0,102,204));
        exitlab.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_exitlabMouseExited

    private void SUMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUMEN
        // TODO add your handling code here:
        signpan.setBackground(new java.awt.Color(204,204,204));
        signlab.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_SUMEN

    private void SUMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUMEX
        // TODO add your handling code here:
        signpan.setBackground(new java.awt.Color(0,102,204));
        signlab.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_SUMEX
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bck;
    private javax.swing.JLabel exitlab;
    private javax.swing.JPanel expan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel loglab;
    private javax.swing.JPanel logpan;
    private javax.swing.JLabel minlab;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField pwdtf;
    private javax.swing.JLabel signlab;
    private javax.swing.JPanel signpan;
    private javax.swing.JLabel statuslab;
    // End of variables declaration//GEN-END:variables
}
