/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinedb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author theam
 */
public class manageEMPS extends javax.swing.JFrame {
    static String loggedUname=null;
    static String loggedUid=null;
    /**
     * Creates new form manageEMPS
     */
    public manageEMPS() {
        initComponents();
    }
    public void OnStart(String logID,String logName){
        LoadEMPS(selectEMPcb);
        LoadEMPS(desCB);
        loggedUname=logName;
        loggedUid=logID;
    }
    private boolean isAdmin(String uid){
        boolean res=false;
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from user where userid='"+uid+"' and PL='A' ";
              //  JOptionPane.showMessageDialog(null,"Passing uid: "+uid);
                
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    res=true;
                }else{
                    res=false;
                }
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error with transfer of user id "+e);
        }
       // JOptionPane.showMessageDialog(null,"Result of check: "+res);
        return res;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdtf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        aepan = new javax.swing.JPanel();
        aelab = new javax.swing.JLabel();
        statuslab = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        desCB = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        plistcb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cdpan = new javax.swing.JPanel();
        cdlab = new javax.swing.JLabel();
        statuslab4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nnametf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        npwd1 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        npwd2 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        upan = new javax.swing.JPanel();
        ulab = new javax.swing.JLabel();
        statuslab5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        statuslab1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        selectEMPcb = new javax.swing.JComboBox<>();
        repan = new javax.swing.JPanel();
        relab = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        repan1 = new javax.swing.JPanel();
        relab1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        semptf = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        statuslab2 = new javax.swing.JLabel();
        statuslab3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    < BACK");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 654, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        jLabel2.setText("Enter Employee details");

        jLabel3.setText("Enter name");

        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter password");

        pwdtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdtfActionPerformed(evt);
            }
        });

        jLabel5.setText("This will be set to the username by default if nothing is entered");

        jLabel6.setText("Designation");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Support" }));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 204));

        aepan.setBackground(new java.awt.Color(0, 102, 204));

        aelab.setForeground(new java.awt.Color(255, 255, 255));
        aelab.setText("      ADD EMPLOYEE");
        aelab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AEMCLK(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AEMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AEMEX(evt);
            }
        });

        javax.swing.GroupLayout aepanLayout = new javax.swing.GroupLayout(aepan);
        aepan.setLayout(aepanLayout);
        aepanLayout.setHorizontalGroup(
            aepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aelab, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        aepanLayout.setVerticalGroup(
            aepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aelab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nametf)
                            .addComponent(pwdtf)
                            .addComponent(jComboBox1, 0, 189, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(aepan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statuslab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statuslab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aepan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add employee", jPanel2);

        jLabel11.setText("Select the employee to Promote/Demote");

        jLabel12.setText("Employee username");

        jLabel13.setText("Select designation");

        plistcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Support" }));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/refresh_icon.png"))); // NOI18N
        jLabel14.setText("Refresh");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });

        cdpan.setBackground(new java.awt.Color(0, 102, 204));
        cdpan.setForeground(new java.awt.Color(255, 255, 255));
        cdpan.setToolTipText("");

        cdlab.setForeground(new java.awt.Color(255, 255, 255));
        cdlab.setText("         CHANGE DESIGNATION");
        cdlab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cdlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CDMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CDMEX(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CDMCLK(evt);
            }
        });

        javax.swing.GroupLayout cdpanLayout = new javax.swing.GroupLayout(cdpan);
        cdpan.setLayout(cdpanLayout);
        cdpanLayout.setHorizontalGroup(
            cdpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cdlab, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        cdpanLayout.setVerticalGroup(
            cdpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cdlab, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statuslab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cdpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(plistcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)))
                        .addGap(0, 322, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(desCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(plistcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cdpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statuslab4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Designations", jPanel4);

        jLabel15.setText("Enter updated details");

        jLabel16.setText("New alias");

        jLabel17.setText("password");

        jLabel18.setText("Re-enter password");

        jSeparator4.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator4.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator4.setToolTipText("");

        upan.setBackground(new java.awt.Color(0, 102, 204));
        upan.setToolTipText("");

        ulab.setForeground(new java.awt.Color(255, 255, 255));
        ulab.setText("           UPDATE");
        ulab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdUC(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UMEX(evt);
            }
        });

        javax.swing.GroupLayout upanLayout = new javax.swing.GroupLayout(upan);
        upan.setLayout(upanLayout);
        upanLayout.setHorizontalGroup(
            upanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ulab, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        upanLayout.setVerticalGroup(
            upanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ulab, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel19.setText("If no changes are made, then the old values will be retained");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(upan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statuslab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(npwd2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(nnametf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npwd1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(nnametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(npwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(npwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statuslab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage your details here", jPanel5);

        jLabel7.setText("Select employee");

        repan.setBackground(new java.awt.Color(0, 102, 204));
        repan.setToolTipText("");

        relab.setForeground(new java.awt.Color(255, 255, 255));
        relab.setText("        REMOVE EMPLOYEE");
        relab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REFC(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REMEX(evt);
            }
        });

        javax.swing.GroupLayout repanLayout = new javax.swing.GroupLayout(repan);
        repan.setLayout(repanLayout);
        repanLayout.setHorizontalGroup(
            repanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(relab, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        repanLayout.setVerticalGroup(
            repanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(relab, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/refresh_icon.png"))); // NOI18N
        jLabel8.setText("Refresh");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 204));

        jLabel9.setText("Search manually");

        repan1.setBackground(new java.awt.Color(0, 102, 204));
        repan1.setToolTipText("");

        relab1.setForeground(new java.awt.Color(255, 255, 255));
        relab1.setText("        REMOVE EMPLOYEE");
        relab1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MdelE(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                relab1REMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                relab1REMEX(evt);
            }
        });

        javax.swing.GroupLayout repan1Layout = new javax.swing.GroupLayout(repan1);
        repan1.setLayout(repan1Layout);
        repan1Layout.setHorizontalGroup(
            repan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(relab1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        repan1Layout.setVerticalGroup(
            repan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(relab1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel10.setText("Enter employee name");

        jSeparator3.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout statuslab1Layout = new javax.swing.GroupLayout(statuslab1);
        statuslab1.setLayout(statuslab1Layout);
        statuslab1Layout.setHorizontalGroup(
            statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statuslab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(statuslab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(statuslab1Layout.createSequentialGroup()
                        .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(statuslab1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(45, 45, 45)
                                .addComponent(selectEMPcb, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(repan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(statuslab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, statuslab1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(semptf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(repan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statuslab1Layout.setVerticalGroup(
            statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statuslab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(selectEMPcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(repan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statuslab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(semptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(repan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(statuslab3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statuslab2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Employee", statuslab1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 730, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
                           SupportMenu sm=new SupportMenu();
                           sm.setVisible(true);
                           this.dispose();
    }//GEN-LAST:event_jLabel1MousePressed
     private void SetHoverThemeFor(JLabel lb,JPanel pan){
        pan.setBackground(new java.awt.Color(204,204,204));
        lb.setForeground(new java.awt.Color(0,0,0));
    }
    private void ResetHoverThemeFor(JLabel lb,JPanel pan){
        pan.setBackground(new java.awt.Color(0,102,204));
        lb.setForeground(new java.awt.Color(255,255,255));
    }
    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void pwdtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdtfActionPerformed

    private void AEMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AEMEN
        // TODO add your handling code here:
        SetHoverThemeFor(aelab,aepan);
    }//GEN-LAST:event_AEMEN

    private void AEMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AEMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(aelab,aepan);
    }//GEN-LAST:event_AEMEX
    private String getDesgCode(String cinp){
        if(cinp.equals("Administrator")){
            return "A";
        }else{
            return "S";
        }
        
    }
    private void AEMCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AEMCLK
        // TODO add your handling code here:
        String ename=nametf.getText().trim();
        String pwd=pwdtf.getText();
        String desgS=jComboBox1.getSelectedItem().toString().trim();
        String des=getDesgCode(desgS);
        
        
        if(!isAdmin(loggedUid)){
            statuslab.setText("You do not have permission to execute this operation");
            return;
        }
        
        if(isNotEMP(ename)){
            
            if(!isNotEMP(pwd)){
                pwd=ename;
            }
            try{
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                String sql="select * from user where uname='"+ename+"'";
                String sql1="insert into user(uname,upwd,PL) values('"+ename+"','"+pwd+"','"+des+"')";
                
               ResultSet rs=stmt.executeQuery(sql);
               
               if(rs.next()){
                   statuslab.setText("That employee already exists");
               }else{
                   stmt1.executeUpdate(sql1);
                   statuslab.setText("Added employee");
               }
               
            }catch(Exception e){
                
            }
            
        }else{
            statuslab.setText("Enter something for employee name");
        }
        
        
    }//GEN-LAST:event_AEMCLK

    private void REMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMEN
        // TODO add your handling code here:
        SetHoverThemeFor(relab,repan);
    }//GEN-LAST:event_REMEN

    private void REMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(relab,repan);
    }//GEN-LAST:event_REMEX

    private void relab1REMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relab1REMEN
        // TODO add your handling code here:
        SetHoverThemeFor(relab1,repan1);
    }//GEN-LAST:event_relab1REMEN

    private void relab1REMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relab1REMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(relab1,repan1);
    }//GEN-LAST:event_relab1REMEX

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
       LoadEMPS(selectEMPcb);
    }//GEN-LAST:event_jLabel8MousePressed

    private void MdelE(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MdelE
        // TODO add your handling code here:
        String ename=semptf.getText().trim();
        
        if(!isAdmin(loggedUid)){
            statuslab2.setText("You do not have permission to execute this operation");
            return;
        }
        
        
        if(ename.equals("admin")){
            statuslab2.setText("Can't delete this account");
            statuslab3.setText("Can't delete this account");
            return;
        }
        
        if(isNotEMP(ename)){
            try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                String sql="select * from user where uname='"+ename+"' and PL='A' or uname='"+ename+"' and PL='S'";
                String sql1="delete from user where uname='"+ename+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    
                    stmt1.executeUpdate(sql1);
                    statuslab2.setText("Employee removed");
                    
                }else{
                    statuslab3.setText("No such employee found");
                }
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
        }else{
            statuslab3.setText("Enter something in the employee name field");
        }
        
    }//GEN-LAST:event_MdelE

    private void REFC(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFC
        // TODO add your handling code here:
        String ename=selectEMPcb.getSelectedItem().toString().trim();
        if(!isAdmin(loggedUid)){
            statuslab2.setText("You do not have permission to execute this operation");
            return;
        }
        if(ename.equals("admin")){
            statuslab2.setText("Can't delete this account");
            return;
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                String sql="select * from user where uname='"+ename+"' and PL='A' or uname='"+ename+"' and PL='S'";
            
                String sql1="delete from user where uname='"+ename+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    
                    stmt1.executeUpdate(sql1);
                    statuslab2.setText("Employee removed");
                    
                }else{
                    statuslab2.setText("No such employee found");
                }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
        
    }//GEN-LAST:event_REFC

    private void CDMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CDMEN
        // TODO add your handling code here:
        SetHoverThemeFor(cdlab,cdpan);
    }//GEN-LAST:event_CDMEN

    private void CDMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CDMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(cdlab,cdpan);
    }//GEN-LAST:event_CDMEX

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
        LoadEMPS(desCB);
    }//GEN-LAST:event_jLabel14MousePressed

    private void CDMCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CDMCLK
        // TODO add your handling code here:
        String sname=desCB.getSelectedItem().toString();
        String selD=plistcb.getSelectedItem().toString();
        String sdes=getDesgCode(selD);
        
        if(!isAdmin(loggedUid)){
            statuslab4.setText("You don't have the permission to perform this operation");
        return;    
        }
        if(sname.equals("admin")){
            statuslab4.setText("This account can't be altered");
            return;
        }
        try{
             Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="update user set PL='"+sdes+"' where uname='"+sname+"'";
             //   JOptionPane.showMessageDialog(null,"New PL: "+sdes);
                stmt.executeUpdate(sql);
                statuslab4.setText("changed designation to "+selD);
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
        
        
        
        
    }//GEN-LAST:event_CDMCLK

    private void UMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UMEN
        // TODO add your handling code here:
        SetHoverThemeFor(ulab,upan);
    }//GEN-LAST:event_UMEN

    private void UMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UMEX
        // TODO add your handling code here:
         ResetHoverThemeFor(ulab,upan);
    }//GEN-LAST:event_UMEX

    private void UpdUC(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdUC
        // TODO add your handling code here:
        String newname=nnametf.getText().trim();
        String newpwd1=npwd1.getText();
        String newpwd2=npwd2.getText();
        
        if(loggedUname.equals("admin")){
            statuslab5.setText("Can't alter this account");
            return;
        }
        
        
        try{
             Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                Statement stmt2=con.createStatement();
                
                String sql1="select * from user where uname='"+loggedUname+"'";
                
                ResultSet rs1=stmt1.executeQuery(sql1);
                if(rs1.next()){
                    
                    String oldname=rs1.getString(2);
                    String oldpwd=rs1.getString(3);
                    
                    String finalname=oldname;
                    String finalpwd =oldpwd;
                    
                    if(!newpwd1.equals(oldpwd)&&isNotEMP(newpwd1)){
                        if(newpwd1.equals(newpwd2)){
                        finalpwd=newpwd1;
                        }else{
                        statuslab5.setText("Passwords don't match");
                        return;
                    }
                    }else if(!isNotEMP(newpwd1)&&!isNotEMP(newpwd2)){
                        finalpwd=oldpwd;
                    }
                    if(isNotEMP(newname)&&!newname.equals(oldname)){
                        finalname=newname;
                    }else{
                        finalname=oldname;
                    }
                    String sql="select * from user where uname='"+finalname+"' and not userid='"+loggedUid+"'";
                   ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    statuslab5.setText("That name already exists, use a different name");
                    
                }else{
                    String sql2="update user set uname='"+finalname+"',upwd='"+finalpwd+"' where userid='"+loggedUid+"'";
                    stmt2.executeUpdate(sql2);
                    loggedUname=finalname;
                    statuslab5.setText("Updated details");
                } 
                }else{
                    JOptionPane.showMessageDialog(null, "Error in passing logged uname ");
                }
                
                
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
        
    }//GEN-LAST:event_UpdUC
    private void LoadEMPS(JComboBox cbox){
         String[] names=null;
        int counter=0;
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                String sql="select * from user where PL='A' or PL='S'";
                String sql1="select count(*) from user where PL='A' or PL='S'";
                
                ResultSet rs1=stmt1.executeQuery(sql1);
                
                if(rs1.next()){
                    
                    int len=rs1.getInt(1);
                    names=new String[len];
                    ResultSet rs=stmt.executeQuery(sql);
                    
                  //  JOptionPane.showMessageDialog(null,"no of res: "+len);
                    
                while(rs.next())
                {
                    String temp=rs.getString(2);
                    names[counter]=temp;
                    counter++;
                }
               // DefaultComboBoxModel<String> aModel=selectEMPcb.getModel()<String>;
                cbox.setModel(new DefaultComboBoxModel<>(names));
                    
                }else{
                    statuslab2.setText("No Employees found");
                }
                
               
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }
    
    
    
    private boolean isNotEMP(String str){
        
        if(str==null||str.equals("")){
            return false;
        }else{
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageEMPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageEMPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageEMPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageEMPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageEMPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aelab;
    private javax.swing.JPanel aepan;
    private javax.swing.JLabel cdlab;
    private javax.swing.JPanel cdpan;
    private javax.swing.JComboBox<String> desCB;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField nnametf;
    private javax.swing.JPasswordField npwd1;
    private javax.swing.JPasswordField npwd2;
    private javax.swing.JComboBox<String> plistcb;
    private javax.swing.JPasswordField pwdtf;
    private javax.swing.JLabel relab;
    private javax.swing.JLabel relab1;
    private javax.swing.JPanel repan;
    private javax.swing.JPanel repan1;
    private javax.swing.JComboBox<String> selectEMPcb;
    private javax.swing.JTextField semptf;
    private javax.swing.JLabel statuslab;
    private javax.swing.JPanel statuslab1;
    private javax.swing.JLabel statuslab2;
    private javax.swing.JLabel statuslab3;
    private javax.swing.JLabel statuslab4;
    private javax.swing.JLabel statuslab5;
    private javax.swing.JLabel ulab;
    private javax.swing.JPanel upan;
    // End of variables declaration//GEN-END:variables
}
