/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinedb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class S_manage_bookings extends javax.swing.JFrame {
     String loggedUname=null;
     String loggedUid=null;
    /**
     * Creates new form S_manage_bookings
     */
    public S_manage_bookings() {
        initComponents();
    }
     public void OnStart(String logID,String logName){
        
        loggedUname=logName;
        loggedUid=logID;
    }
     
     private void LoadTripIDS(JComboBox cbox){
         
         String[] tripids=null;
         int nTrips=0;
         int tc=0;
         try{
             
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                String sql="select tripID from flighttimings";
                String sql1="select count(*) from flighttimings";
                
                
                ResultSet rs1=stmt1.executeQuery(sql1);
                if(rs1.next()){
                    nTrips=rs1.getInt(1);
                    tripids=new String[nTrips];
                    ResultSet rs=stmt.executeQuery(sql);
                     while(rs.next()){
                     tripids[tc]=rs.getString(1);
                     tc++;
                     
                     cbox.setModel(new DefaultComboBoxModel<>(tripids));
                     
                }
                }else{
                    statuslab.setText("Error with connection with db");
                }
               
               
                
                
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,"Error: "+e);
         
         }
     }
     private void loadPassengers(JComboBox cbox,String tripid){
         String[] pnames=null;
         int nTrips=0;
         int tc=0;
         try{
             
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                String sql="select cid from reserve where tripID='"+tripid+"'";
                String sql1="select count(*) from reserve where tripID='"+tripid+"'";
                
                
                ResultSet rs1=stmt1.executeQuery(sql1);
                if(rs1.next()){
                    nTrips=rs1.getInt(1);
                    pnames=new String[nTrips];
                    ResultSet rs=stmt.executeQuery(sql);
                     while(rs.next()){
                     pnames[tc]=rs.getString(1);
                     tc++;
                     
                     cbox.setModel(new DefaultComboBoxModel<>(pnames));
                     
                }
                }else{
                    statuslab.setText("Error with connection with db");
                }
               
               
                
                
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,"Error: "+e);
         
         }
     }
     private void SetPassengerInfo(String name,String seatno,String planeno){
         pnamelab.setText("Passenger name: "+name);
         psnolab.setText("Seat number: "+seatno);
         pplno.setText("Plane no: "+planeno);
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectTripIDcb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        n1pan = new javax.swing.JPanel();
        n1lab = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        selectPassengercb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        n2pan = new javax.swing.JPanel();
        n2lab = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnamelab = new javax.swing.JLabel();
        psnolab = new javax.swing.JLabel();
        pplno = new javax.swing.JLabel();
        statuslab = new javax.swing.JLabel();
        rp1pan = new javax.swing.JPanel();
        rp1lab = new javax.swing.JLabel();
        rp2pan = new javax.swing.JPanel();
        rp2lab = new javax.swing.JLabel();
        customseatff = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setToolTipText("");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("   <   BACK");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 565, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        jLabel1.setText("Select the flight particulars");

        jLabel2.setText("Trip ID");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/refresh_icon.png"))); // NOI18N
        jLabel3.setText("refresh");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        n1pan.setBackground(new java.awt.Color(0, 102, 204));
        n1pan.setToolTipText("");

        n1lab.setForeground(new java.awt.Color(255, 255, 255));
        n1lab.setText("           NEXT");
        n1lab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n1lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TNBCLK(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N1MEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N1MEX(evt);
            }
        });

        javax.swing.GroupLayout n1panLayout = new javax.swing.GroupLayout(n1pan);
        n1pan.setLayout(n1panLayout);
        n1panLayout.setHorizontalGroup(
            n1panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n1lab, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        n1panLayout.setVerticalGroup(
            n1panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n1lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 204));

        jLabel4.setText("select passenger");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/refresh_icon.png"))); // NOI18N
        jLabel5.setText("refresh");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        n2pan.setBackground(new java.awt.Color(0, 102, 204));

        n2lab.setForeground(new java.awt.Color(255, 255, 255));
        n2lab.setText("           NEXT");
        n2lab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n2lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PSMCLK(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N2MEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N2MEX(evt);
            }
        });

        javax.swing.GroupLayout n2panLayout = new javax.swing.GroupLayout(n2pan);
        n2pan.setLayout(n2panLayout);
        n2panLayout.setHorizontalGroup(
            n2panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n2lab, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        n2panLayout.setVerticalGroup(
            n2panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n2lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator2.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 204));

        pnamelab.setText("Name:");

        psnolab.setText("Seat no:");

        pplno.setText("Plane no:");

        rp1pan.setBackground(new java.awt.Color(0, 102, 204));

        rp1lab.setForeground(new java.awt.Color(255, 255, 255));
        rp1lab.setText("          Remove passenger from plane");
        rp1lab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rp1lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RPMCLK(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RPMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RPMEX(evt);
            }
        });

        javax.swing.GroupLayout rp1panLayout = new javax.swing.GroupLayout(rp1pan);
        rp1pan.setLayout(rp1panLayout);
        rp1panLayout.setHorizontalGroup(
            rp1panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rp1lab, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        rp1panLayout.setVerticalGroup(
            rp1panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rp1lab, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        rp2pan.setBackground(new java.awt.Color(0, 102, 204));

        rp2lab.setForeground(new java.awt.Color(255, 255, 255));
        rp2lab.setText("      Relocate passenger to different seat");
        rp2lab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rp2lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RP2MEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RP2MEX(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RPDSMCLK(evt);
            }
        });

        javax.swing.GroupLayout rp2panLayout = new javax.swing.GroupLayout(rp2pan);
        rp2pan.setLayout(rp2panLayout);
        rp2panLayout.setHorizontalGroup(
            rp2panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rp2lab, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );
        rp2panLayout.setVerticalGroup(
            rp2panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rp2lab, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        customseatff.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel10.setText("Enter custom valid seat number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statuslab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(selectTripIDcb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(n1pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83)
                                .addComponent(selectPassengercb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n2pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnamelab)
                            .addComponent(pplno)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(psnolab)
                                    .addComponent(rp1pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customseatff, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(rp2pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectTripIDcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(n1pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(selectPassengercb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(n2pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnamelab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psnolab)
                    .addComponent(jLabel10))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pplno)
                    .addComponent(customseatff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rp1pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(statuslab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rp2pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("remove/relocate passenger", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PSMCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PSMCLK
        // TODO add your handling code here:
        String currPass=selectPassengercb.getSelectedItem().toString();
        String currTrip=selectTripIDcb.getSelectedItem().toString();

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/airdb","root","");

            Statement stmt=con.createStatement();
            String sql="select * from reserve where tripID='"+currTrip+"' and cid='"+currPass+"'";
            ResultSet rs=stmt.executeQuery(sql);
            if(rs.next()){
                String s1=getPName(currPass);
                String s2=rs.getString(3);
                String s3=rs.getString(4);

                SetPassengerInfo(s1,s2,s3);

            }else{
                statuslab.setText("Error trying to find data at pass info");
            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_PSMCLK

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        String currentTrip=selectTripIDcb.getSelectedItem().toString();
        loadPassengers(selectPassengercb,currentTrip);
    }//GEN-LAST:event_jLabel5MousePressed

    private void TNBCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TNBCLK
        // TODO add your handling code here:
        String currentTrip=selectTripIDcb.getSelectedItem().toString();
        loadPassengers(selectPassengercb,currentTrip);
    }//GEN-LAST:event_TNBCLK

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LoadTripIDS(selectTripIDcb);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        SupportMenu sm=new SupportMenu();
        sm.OnStart(loggedUname,loggedUid);
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MousePressed

    private void RPMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMEN
        // TODO add your handling code here:
         AirlineDB.SetHoverTheme(rp1lab, rp1pan);
    }//GEN-LAST:event_RPMEN

    private void RPDSMCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPDSMCLK
        // TODO add your handling code here:
        //CODE TO RELOCATE POSITION HERE
        String currPass=selectPassengercb.getSelectedItem().toString();
        String currTrip=selectTripIDcb.getSelectedItem().toString();
        int oldseat=getcurrseat(currTrip,currPass);
        int newseat=Integer.parseInt(customseatff.getText().trim());
        //code to remove selected passenger from plane
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root","");
                Statement stmt=con.createStatement();
                String sql="update reserve set seatno='"+newseat+"' where cid='"+currPass+"' and tripID='"+currTrip+"'";
                
                if(isSeatAvailable(currTrip,newseat)){
                    stmt.executeUpdate(sql);
                    statuslab.setText("Relocated to new seat");
                }else{
                    statuslab.setText("That seat is already taken, choose another");
                }
                
                
                
                
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }//GEN-LAST:event_RPDSMCLK

    private void N1MEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1MEN
        // TODO add your handling code here:
        AirlineDB.SetHoverTheme(n1lab, n1pan);
    }//GEN-LAST:event_N1MEN

    private void N1MEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1MEX
        // TODO add your handling code here:
        AirlineDB.ResetHoverTheme(n1lab, n1pan);
    }//GEN-LAST:event_N1MEX

    private void N2MEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N2MEN
        // TODO add your handling code here:
         AirlineDB.SetHoverTheme(n2lab, n2pan);
    }//GEN-LAST:event_N2MEN

    private void N2MEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N2MEX
        // TODO add your handling code here:
        AirlineDB.ResetHoverTheme(n2lab, n2pan);
    }//GEN-LAST:event_N2MEX

    private void RPMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMEX
        // TODO add your handling code here:
       AirlineDB.ResetHoverTheme(rp1lab, rp1pan);
    }//GEN-LAST:event_RPMEX

    private void RPMCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMCLK
        // TODO add your handling code here:
        String currPass=selectPassengercb.getSelectedItem().toString();
        String currTrip=selectTripIDcb.getSelectedItem().toString();
        
        int occseats=getoccseats(currTrip);
        int foc=occseats-1;
        //code to remove selected passenger from plane
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root","");
                Statement stmt=con.createStatement();
                String sql="delete from reserve where cid='"+currPass+"' and tripID='"+currTrip+"'";
                stmt.executeUpdate(sql);
                updateOC(currTrip,foc);
                statuslab.setText("removed user");
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }//GEN-LAST:event_RPMCLK
    private void updateOC(String tripid,int ocs){
      
        try{
            Class.forName("com.mysql.jdbc.Driver");                
                Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/airdb", "root", "");                
                Statement stmt = con.createStatement();
                 String sql1="update flighttimings set occseats='"+ocs+"' where tripID='"+tripid+"'";
                 stmt.executeUpdate(sql1);
                
        }catch(Exception e){
            
        }
    }
    private int getoccseats(String tripid){
        int oc=0;
        try {
                Class.forName("com.mysql.jdbc.Driver");                
                Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/airdb", "root", "");                
                Statement stmt = con.createStatement();
                String sql = "select occseats from flighttimings where tripID='" + tripid + "'";
                 ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                  oc=rs.getInt(1);
                }else{
                  oc=0;
        }
        }catch(Exception e){
            
        }
       return oc;
    }
    private void RP2MEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RP2MEN
        // TODO add your handling code here:
        AirlineDB.SetHoverTheme(rp2lab, rp2pan);
    }//GEN-LAST:event_RP2MEN

    private void RP2MEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RP2MEX
        // TODO add your handling code here:
        AirlineDB.ResetHoverTheme(rp2lab, rp2pan);
    }//GEN-LAST:event_RP2MEX
    private int getcurrseat(String tripid,String cid){
        int retres=0;
        
        try{
           
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root","");
                Statement stmt=con.createStatement();
                String sql="select seatno from reserve where cid='"+cid+"' and tripID='"+tripid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    retres=Integer.parseInt(rs.getString(1));
                }else{
                    statuslab.setText("Can't find old seat");
                }
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
        
        return retres;
    }
    private boolean isSeatAvailable(String tripid, int os){
        boolean retres=false;
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root","");
                Statement stmt=con.createStatement();
                String sql="select * from reserve where tripID='"+tripid+"' and seatno='"+os+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    retres=false;
                }else{
                    retres=true;
                }
        }catch(Exception e){
            
        }
        return retres;
    }
    private String getPName(String cid){
        String ret=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/airdb","root",""); 
                
                JOptionPane.showMessageDialog(null, "Passing as cid: "+cid);
                Statement stmt=con.createStatement();
                String sql="select uname from user where userid='"+cid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                    ret=rs.getString(1);
                }else{
                    statuslab.setText("Error: check querry at passenger details retrieval");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
        return ret;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_manage_bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_manage_bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_manage_bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_manage_bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_manage_bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField customseatff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel n1lab;
    private javax.swing.JPanel n1pan;
    private javax.swing.JLabel n2lab;
    private javax.swing.JPanel n2pan;
    private javax.swing.JLabel pnamelab;
    private javax.swing.JLabel pplno;
    private javax.swing.JLabel psnolab;
    private javax.swing.JLabel rp1lab;
    private javax.swing.JPanel rp1pan;
    private javax.swing.JLabel rp2lab;
    private javax.swing.JPanel rp2pan;
    private javax.swing.JComboBox<String> selectPassengercb;
    private javax.swing.JComboBox<String> selectTripIDcb;
    private javax.swing.JLabel statuslab;
    // End of variables declaration//GEN-END:variables
}
