/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinedb;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author theam
 */
public class SupportMenu extends javax.swing.JFrame {
    static String loggedUname=null;
    static String loggedUid=null;
    /**
     * Creates new form SupportMenu
     */
    public SupportMenu() {
        initComponents();
    }
    public void OnStart(String logID, String logName){
        loggedUname=logName;
        loggedUid=logID;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cfpan = new javax.swing.JPanel();
        cflab = new javax.swing.JLabel();
        cppan = new javax.swing.JPanel();
        cplab = new javax.swing.JLabel();
        mepan = new javax.swing.JPanel();
        melab = new javax.swing.JLabel();
        mppan = new javax.swing.JPanel();
        mplab = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 320));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cfpan.setBackground(new java.awt.Color(0, 102, 204));

        cflab.setForeground(new java.awt.Color(255, 255, 255));
        cflab.setText("                                   CHECK FLIGHTS");
        cflab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cflab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CFMCLK(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CFMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CFMEX(evt);
            }
        });

        javax.swing.GroupLayout cfpanLayout = new javax.swing.GroupLayout(cfpan);
        cfpan.setLayout(cfpanLayout);
        cfpanLayout.setHorizontalGroup(
            cfpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cflab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cfpanLayout.setVerticalGroup(
            cfpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cflab, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        cppan.setBackground(new java.awt.Color(0, 102, 204));

        cplab.setForeground(new java.awt.Color(255, 255, 255));
        cplab.setText("                        CHECK PLANE STATUS FOR TRIPS");
        cplab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cplab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPST(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CPMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CPMEX(evt);
            }
        });

        javax.swing.GroupLayout cppanLayout = new javax.swing.GroupLayout(cppan);
        cppan.setLayout(cppanLayout);
        cppanLayout.setHorizontalGroup(
            cppanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cplab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cppanLayout.setVerticalGroup(
            cppanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cplab, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        mepan.setBackground(new java.awt.Color(0, 102, 204));

        melab.setForeground(new java.awt.Color(255, 255, 255));
        melab.setText("                                 MANAGE BOOKINGS");
        melab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        melab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MBCLK(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MEMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MEMEX(evt);
            }
        });

        javax.swing.GroupLayout mepanLayout = new javax.swing.GroupLayout(mepan);
        mepan.setLayout(mepanLayout);
        mepanLayout.setHorizontalGroup(
            mepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(melab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mepanLayout.setVerticalGroup(
            mepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(melab, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        mppan.setBackground(new java.awt.Color(0, 102, 204));
        mppan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MPMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MPMEX(evt);
            }
        });

        mplab.setForeground(new java.awt.Color(255, 255, 255));
        mplab.setText("                   MANAGE EMPLOYEES AND PRIVILAGES");
        mplab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mplab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MPMEN(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MPMEX(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mplabMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mppanLayout = new javax.swing.GroupLayout(mppan);
        mppan.setLayout(mppanLayout);
        mppanLayout.setHorizontalGroup(
            mppanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mplab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        mppanLayout.setVerticalGroup(
            mppanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mplab, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel2.setBackground(new java.awt.Color(0,0,0,150));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cppan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mepan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mppan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cfpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cfpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cppan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mepan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(mppan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 290));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   LOGOUT");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 575, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinedb/ctint.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 660, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
    private void SetHoverThemeFor(JLabel lb,JPanel pan){
        pan.setBackground(new java.awt.Color(204,204,204));
        lb.setForeground(new java.awt.Color(0,0,0));
    }
    private void ResetHoverThemeFor(JLabel lb,JPanel pan){
        pan.setBackground(new java.awt.Color(0,102,204));
        lb.setForeground(new java.awt.Color(255,255,255));
    }
    private void CFMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CFMEN
        // TODO add your handling code here:
        SetHoverThemeFor(cflab,cfpan);
    }//GEN-LAST:event_CFMEN

    private void CFMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CFMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(cflab,cfpan);
    }//GEN-LAST:event_CFMEX

    private void CPMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPMEN
        // TODO add your handling code here:
       SetHoverThemeFor(cplab,cppan);
    }//GEN-LAST:event_CPMEN

    private void CPMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(cplab,cppan);
    }//GEN-LAST:event_CPMEX

    private void MEMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMEN
        // TODO add your handling code here:
        SetHoverThemeFor(melab,mepan);
    }//GEN-LAST:event_MEMEN

    private void MEMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(melab,mepan);
    }//GEN-LAST:event_MEMEX

    private void MPMEN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MPMEN
        // TODO add your handling code here:
        SetHoverThemeFor(mplab,mppan);
    }//GEN-LAST:event_MPMEN

    private void MPMEX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MPMEX
        // TODO add your handling code here:
        ResetHoverThemeFor(mplab,mppan);
    }//GEN-LAST:event_MPMEX

    private void mplabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mplabMousePressed
        // TODO add your handling code here:
        manageEMPS me=new manageEMPS();
        me.OnStart(loggedUid,loggedUname);
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mplabMousePressed

    private void CFMCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CFMCLK
        // TODO add your handling code here:
        CheckFlights cf=new CheckFlights();
        cf.OnCreate(loggedUid, loggedUname);
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CFMCLK

    private void MBCLK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MBCLK
        // TODO add your handling code here:
        S_manage_bookings smb=new S_manage_bookings();
        smb.OnStart(loggedUname,loggedUid);
        smb.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_MBCLK

    private void CPST(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPST
        // TODO add your handling code here:
        Cpst cp=new Cpst();
        cp.OnStart(loggedUname, loggedUid);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CPST
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupportMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bck;
    private javax.swing.JLabel cflab;
    private javax.swing.JPanel cfpan;
    private javax.swing.JLabel cplab;
    private javax.swing.JPanel cppan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel melab;
    private javax.swing.JPanel mepan;
    private javax.swing.JLabel mplab;
    private javax.swing.JPanel mppan;
    // End of variables declaration//GEN-END:variables
}
